
target:推盟 do
platform :ios, '5.0' #手机的系统

pod 'JSONKit', '~> 1.5pre'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics', '~> 3.5.8'
#友盟分享
pod 'UMengSocialCOM', '~> 5.2.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'UMengFeedback', '~> 2.3.1'
pod 'MYIntroduction', '~> 0.0.1'
pod 'SDCycleScrollView', '~> 1.3'
pod 'MagicalRecord', '~> 2.3.0'
pod 'MMDrawerController', '~> 0.6.0'
pod 'DJWStarRatingView', '~> 0.0.4'
pod 'CSNPlaceholderTextView', '~> 0.0.4'
pod 'NRImagePickerController', '~> 1.1.4'

pod 'Masonry', '~> 0.6.4'

pod 'UIAlertView+Blocks', '~> 0.9'

#高德地图
pod 'AMapLocation', '~> 1.2.2'
pod 'AMap2DMap', '~> 3.3.0'
pod 'AMapSearch', '~> 3.3.0'

